version: "3.4"
services:
    servicea:
      build:
        context: service/.
      expose:
        - 4000
      networks:
        - default
    serviceb:
      build:
        context: service/.
      expose:
        - 4000
      networks:
        - default
    servicec:
      build:
        context: service/.
      expose:
        - 4000
      networks:
        - default
    load_balancer:
      image: nginx:latest
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - 80:80
      networks:
        - default
networks:
  default:
    driver: bridge
